### ISSUE TITLE
Linux下使用的问题

### ISSUE THREAD

**Issue by scbizu** [wangtao2132/sxDesk#3]
菊苣你好，这个repos支持Linux下拨号上网的吗？我试了下 好像不可以诶(没时间造轮子 所以找了下  发现最近更新的只有这个repos惹  ) 对菊苣的无私奉献精神点个star！

**Comment by WrBug** [comment]
目前只支持Windows的拨号。linux没时间折腾，可以用java运行shell脚本方式来实现。Windows的实现就是java运行exe程序实现的
